import { Location } from "@/lib/common/types/location";

export const LOCATIONS: Location[] = [
    {
        id: 1,
        name: "Keiservarden, Bodø",
        lat: 67.315278,
        long: 14.478333,
        elevation: 366,
        timezone: "Europe/Oslo",
        windDirections: ['N', 'NW', 'W'],
    },
    {
        id: 2,
        name: "Hoven, Gimsøya",
        lat: 68.332778,
        long: 14.110278,
        elevation: 368,
        timezone: "Europe/Oslo",
        windDirections: ['NW', 'N', 'NE', 'E', 'SE', 'S', 'SW'],
    },
    {
        id: 3,
        name: "Liaset, Voss",
        lat: 60.703333,
        long: 6.521389,
        elevation: 650,
        timezone: "Europe/Oslo",
        windDirections: ['NW', 'N', 'SW', 'W'],
    },
    {
        id: 4,
        name: "Hangur, sør-start, Voss",
        lat: 60.638889,
        long: 6.403056,
        elevation: 660,
        timezone: "Europe/Oslo",
        windDirections: ['SW', 'S', 'SE'],
    },
    {
        id: 5,
        name: "Salknappen (Riksanlegget), Vågå",
        lat: 61.900278,
        long: 9.245278,
        elevation: 1250,
        timezone: "Europe/Oslo",
        windDirections: ['SW', 'S', 'SE'],
    },
    {
        id: 6,
        name: "Grøtterud , Hvittingfoss",
        lat: 59.504722,
        long: 9.998056,
        elevation: 350,
        timezone: "Europe/Oslo",
        windDirections: ['SW', 'S', 'SE'],
    },
    {
        id: 7,
        name: "Sundvollen, Viken",
        lat: 60.053889,
        long: 10.322500,
        elevation: 380,
        timezone: "Europe/Oslo",
        windDirections: ['NW', 'W', 'N'],
    },
];
